spring:
  elasticjob:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/elastic_job_demo?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    regCenter:
      serverList: 127.0.0.1:2181
      namespace: elasticJobDemo